inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6

inherit_from: .rubocop_todo.yml

Naming/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/*.rake'
    - 'hydra-pcdm.gemspec'
    - 'lib/hydra-editor.rb'
    - 'spec/hydra-editor_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'