language: ruby
sudo: false
rvm:
  - 2.6.1
  - 2.5.3
  - 2.4.5
jdk:
  - oraclejdk8
env:
  matrix:
    - RAILS_VERSION=5.2.2
    - RAILS_VERSION=5.1.6.1
    - RAILS_VERSION=5.0.7.1
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CC_TEST_REPORTER_ID=e52010675d2774ee408c14c0de08c143d0749e59beb6dd729254d1b3ea94c7b1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
