---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-editor
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
  build:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test
    steps:
      - attach_workspace:
          at: ~/
      - samvera/engine_cart_generate:
          cache_key: v1-internal-test-app-{{ checksum "hydra-editor.gemspec" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-<< parameters.rails_version >>-<< parameters.ruby_version >>
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-editor
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
  test:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
    environment:
      CC_TEST_REPORTER_ID: e52010675d2774ee408c14c0de08c143d0749e59beb6dd729254d1b3ea94c7b1
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Download the Code Climate reporter"
          command: |
            curl -L "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64" > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/config
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-editor
      - samvera/parallel_rspec
      - run:
          name: "Submit the exit code to Code Climate"
          command: ./cc-test-reporter after-build --exit-code $?

workflows:
  version: 2
  ci:
    jobs:
      - bundle:
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
      - build:
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
          requires:
            - bundle
      - test:
          name: "ruby2-5-5"
          ruby_version: "2.5.5"
          requires:
            - build
      - test:
          name: "ruby2-6-2"
          ruby_version: "2.6.2"
          requires:
            - build
